---
abstract: 'Client for (Lucene) Solr'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache-Solr
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  Encode: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  Log::Report: 0
  MIME::Types: 0
  Scalar::Util: 0
  Test::More: 0
  Time::HiRes: 0
  URI: 0
  XML::LibXML::Simple: 0
version: 1.00
